[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lazy"
version = "0.1.0"
description = "Minimal Lazy package"
requires-python = ">=3.10"
dependencies = [
  "torch",
  "transformers>=5.16.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["lazy*"]

[tool.yapf]
based_on_style = "google"
column_limit = 80

[tool.isort]
profile = "google"
line_length = 80
